### ISSUE TITLE
Please tag release version

### ISSUE THREAD

**Issue by t-paul** [3MFConsortium/lib3mf#115]
The current version (as advertised by the library itself) is 1.8.0 but the latest tag on the [release page](https://github.com/3MFConsortium/lib3mf/releases) is 1.1.5. For Debian packaging I used fa23ee3837193c2f2951268703713fe3c5cff2b7 as v1.8.0.

Tagging releases will help all external packagers (Linux Distros, MXE, ...) as those normally rely on tags to package and also discover new versions.

**Comment by martinweismann** [comment]
Hi @t-paul,

it was very much overdue to release a new version of lib3mf.

In fact, I did a couple of things:
1. I introduced [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) as development model for lib3mf. This way, our master will always advertise a version which is in fact released.
2. I created a new release [v1.8.1](https://github.com/3MFConsortium/lib3mf/releases/tag/v1.8.1). It includes your latest changes and a couple of other minor improvements since (the non-released commit) fa23ee3 .
3. I tagged fa23ee3 as [v1.8.0-alpha](https://github.com/3MFConsortium/lib3mf/releases/tag/v1.8.0-alpha). Does this suffice for Debian's packaging system? This commit did pass all automatic tests, but I would not guarantee that it is perfectly fine to be released. Thus I would like to keep the "-alpha"-suffix and not make it an official release on the [releases page](https://github.com/3MFConsortium/lib3mf/release).

In any case, thanks for the gentle reminder.
Cheers!

**Comment by t-paul** [comment]
Thanks, that is great. I'm currently waiting for feedback if the package is good to go in, I don't want to restart the review timer in the NEW queue. Once it's approved we should be ok to just follow up with v1.8.1 quickly, so that release is perfect in both timing an version number :smile:.
