### ISSUE TITLE
lib3mf says, e.g., `clipping="inside"` when it should say `clippingmode="inside"`

### ISSUE THREAD

**Issue by pencerw** [3MFConsortium/lib3mf#122]
this is out of compliance with the beamlattice spec: https://github.com/3MFConsortium/spec_beamlattice/blob/master/3MF%20Beam%20Lattice%20Extension.md#11-beamlattice

Hat tip to @KurtRenap for noticing this.

**Comment by martinweismann** [comment]
Well spotted, @KurtRenap .
Both the included schema as well as the implementation have this problem:
https://github.com/3MFConsortium/lib3mf/blob/master/Include/Model/Classes/NMR_ModelConstants.h#L152 
I will make lib3mf write the attribute "clippingmode" instead of "clipping", but allow both "clippingmode" and "clipping" when reading files (to not break older files).
