### ISSUE TITLE
Download older version 3MF source code

### ISSUE THREAD

**Issue by vgurav** [3MFConsortium/lib3mf#177]
Hi ,
I am trying to download older version 3MF specification and source code.
Specifically i am trying to download 1.0.1 and 1.3 source code.
I didn't found this version of source code and specification on git hub 
https://github.com/3MFConsortium/lib3mf/tags 

Could you please provide any links where i can download these older  version (1.0.1 and 1.3) of lib3MF source code and specification.

**Comment by martinweismann** [comment]
Hi @vgurav,

the 3MF consortum have only recently adopted gihub's release-process for both the Specification-documents as well as the implementation of the library, which is why you do not see many entries on the "releases" page of each repository.

Also note that the version of the specification does relate to the version of this library, lib3mf. The library instead has a method
```wrapper->GetSpecificationVersion("http://schemas.microsoft.com/3dmanufacturing/core/2015/02", bIsSupported, nMajor, nMinor, nMicro);```
that returns which version of a certain specification (in this case core) is supported by lib3mf.

For the specification, you can find versions 1.2.2 and 1.2.3 on https://github.com/3MFConsortium/spec_core/releases . We will publish older versions there, too, at some point.

You can find releases of the implementation lib3mf for several versions:
- on https://github.com/3MFConsortium/lib3mf/releases
- in the commit history of this repository (this is not ideal, but even version numbers that have not been released can be found here)
