### ISSUE TITLE
CModelReaderNode093_TextureVertex::OnAttribute throwing when reading a value of "inf"

### ISSUE THREAD

**Issue by kokuda** [3MFConsortium/lib3mf#96]
I have an old 3mf file from an unknown source that is causing an exception to be thrown when reading the "u" attribute of a "texturevertex".

The value in the file is "inf" which is translated to a float value of INFINITY and therefore greater than XML_3MF_MAXIMUMCOORDINATEVALUE.

	if (fabs (m_fU) > XML_3MF_MAXIMUMCOORDINATEVALUE)
		throw CNMRException(NMR_ERROR_INVALIDMODELTEXTURECOORDINATES);

I can believe that this isn't a valid texture coordinate, but I would prefer the ability to load the file and decide what to do with invalid data later rather than failing to load.

Does it make sense to loosen or remove the validity checks on import and let the data through for the user to interpret?

**Comment by martinweismann** [comment]
I agree. We can make this issue a warning instead of an exception.

Do you want to give it a try? A similar occasion for a warning from an exception in the reader is here https://github.com/3MFConsortium/lib3mf/blob/master/Source/Model/Reader/v100/NMR_ModelReaderNode100_BuildItem.cpp#L90 

The good thing about this approach is, that if the user of lib3MF sets its strict mode, (`lib3mf_reader_setstrictmodeactive`), the original exception will be thrown.

**Comment by martinweismann** [comment]
Closing this issue since v2.0.0 has dropped support for v0.93.
